@baseUrl = http://localhost:8080
#@accessToken = 초기값 (로그인 후 자동 세팅됨)

################################
### AUTH
################################

### SIGNUP
POST {{baseUrl}}/api/auth/signup
Content-Type: application/json

{
  "email": "test44444@example.com",
  "password": "Test1234!",
  "username": "test3",
  "admin": false
}

### LOGIN
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "test44444@example.com",
  "password": "Test1234!"
}

> {%
    client.global.set("accessToken", response.body.data.accessToken);
%}

### ADMINLOGIN
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "1234!"
}

> {%
    client.global.set("accessToken", response.body.data.accessToken);
%}

################################
### ENLISTMENT SCHEDULE (입영 가능 일정)
################################

### GET ENLISTMENT LIST
GET {{baseUrl}}/api/enlistment?page=0&size=5
Authorization: Bearer {{accessToken}}

### GET ENLISTMENT DETAIL
GET {{baseUrl}}/api/enlistment/5
Authorization: Bearer {{accessToken}}

### SEARCH ENLISTMENT (기간 조회)
GET {{baseUrl}}/api/enlistment/search?startDate=2026-01-01&endDate=2029-12-01&page=0&size=10
Authorization: Bearer {{accessToken}}

################################
### ENLISTMENT APPLICATION (입영 신청)
################################

### APPLY ENLISTMENT
POST {{baseUrl}}/api/enlistment-applications
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "scheduleId": 5
}

### GET APPLICATION LIST
GET {{baseUrl}}/api/enlistment-applications
Authorization: Bearer {{accessToken}}

### GET APPLICATION DETAIL
GET {{baseUrl}}/api/enlistment-applications/8525
Authorization: Bearer {{accessToken}}

### CANCEL APPLICATION
PATCH {{baseUrl}}/api/enlistment-applications/8525/cancel
Authorization: Bearer {{accessToken}}

################################
### DEFERMENT (연기 신청 / 사용자)
################################

### APPLY DEFERMENT
POST {{baseUrl}}/api/deferments
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "applicationId": 8526,
  "defermentStatus": "ILLNESS",
  "reasonDetail": "다리가 부러져서 치료 후 입대 예정",
  "scheduleId": 25
}

### GET DEFERMENT DETAIL (USER)
GET {{baseUrl}}/api/deferments/1
Authorization: Bearer {{accessToken}}

################################
### ADMIN – ENLISTMENT APPLICATION
################################

### APPROVE APPLICATION (ADMIN)
PATCH {{baseUrl}}/api/admin/enlistment-applications/1/approve
Authorization: Bearer {{accessToken}}

### APPROVE APPLICATION (ADMIN)
PATCH {{baseUrl}}/api/admin/enlistment-applications/approve/bulk
Authorization: Bearer {{accessToken}}

################################
### ADMIN – DEFERMENT
################################

### GET DEFERMENT LIST (ADMIN)
GET {{baseUrl}}/api/admin/deferments?page=0&size=10
Authorization: Bearer {{accessToken}}

### PROCESS DEFERMENT (APPROVE / REJECT)
PATCH {{baseUrl}}/api/admin/deferments/15
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "decisionStatus": "REJECTED"
}

### PROCESS DEFERMENT BULK
PATCH {{baseUrl}}/api/admin/deferments/bulk
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "decisionStatus": "REJECTED"
}

################################
### ADMIN – DASHBOARD
################################

### GET DASHBOARD SUMMARY
GET {{baseUrl}}/api/admin/dashboard/summary
Authorization: Bearer {{accessToken}}

### GET DASHBOARD ENLISTMENT SUMMARY
GET {{baseUrl}}/api/admin/dashboard/enlistment-schedule
Authorization: Bearer {{accessToken}}

### GET DASHBOARD PENDING
GET {{baseUrl}}/api/admin/dashboard/requested
Authorization: Bearer {{accessToken}}

### GET DASHBOARD DEFERMENTS
GET {{baseUrl}}/api/admin/dashboard/deferments
Authorization: Bearer {{accessToken}}
