@baseUrl = http://localhost:8080
@accessToken = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwidXNlclJvbGUiOiJST0xFX0FETUlOIiwiaWF0IjoxNzY4Nzg4MDQxLCJleHAiOjE3Njg3OTE2NDF9.hQ0pm_LRqA2kAyf_PVRFyR2cDawy0vqscs_YadibOSk

### SIGNIN
POST {{baseUrl}}/api/auth/signup
Content-Type: application/json

{
  "email": "testuser3332@example.com",
  "password": "Test1234!",
  "username": "test3",
  "residentNumber": "900101-1234569",
  "admin": false
}


### LOGIN
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "1234!"
}

### 상품 등록 (관리자)
POST http://localhost:8080/api/admin/products
Content-Type: application/json

{
  "name": "test1",
  "price": 12000,
  "description": "test test test test test test",
  "stock": 100
}

### 상품 단건 조회
GET http://localhost:8080/api/products/1

### 상품 목록 조회 (페이징 + 정렬)
GET http://localhost:8080/api/products?page=0&size=10&sort=createdAt&direction=desc

### 상품 수정 (관리자)
PUT http://localhost:8080/api/admin/products/1
Content-Type: application/json

{
  "name": "군용 전투식량 (리뉴얼)",
  "price": 13000,
  "description": "구성품이 개선된 군용 전투식량",
  "stock": 80
}

### 상품 삭제 (관리자)
DELETE http://localhost:8080/api/admin/products/1
